site_name: A tour of pyproject.toml
site_url: https://ageorgoulas.github.io/onefile
theme:
  name: material
nav:
  - introduction.md
  - setup.md
  - packaging.md
  - linting.md
  - type_checking.md
  - appendix.md
