site_name: A tour of pyproject.toml
site_url: https://ageorgoulas.github.io/pyproject-toml
theme:
  name: material
  features:
    - content.tabs.link

nav:
  - index.md
  - introduction.md
  - setup.md
  - packaging.md
  - linting.md
  - type_checking.md
  - appendix.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: Licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>
