name: publish-code
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  publish-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive sample code
        run: zip -r pyproject-sample.zip tutorial-files
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pyproject-sample.zip
          make_latest: true
